/**
 * Places it is a bad idea to send a stranger to photograph.
 *
 * This is a safety rule, not a taste one. A generated hunt points people at a
 * building and asks them to stand outside it taking pictures, and there are
 * places where doing that gets someone questioned by security or worse.
 * Observed live: a Savannah hunt chose a **U.S. Customs and Border
 * Protection** facility as its grand finale — the one stop every route
 * converges on.
 *
 * It lives in the shared contract rather than in the generator because BOTH
 * sides need it. The generator filters candidates out; the browser checks what
 * it was handed, because a hunt generated by an older server — or by any
 * server that skips the filter — still reaches a player through the web app.
 * Defence in depth is warranted when the failure mode is a group of strangers
 * photographing a federal building.
 *
 * Deliberately conservative: a false positive costs one candidate out of
 * dozens; a false negative points people somewhere they should not be.
 */

const UNSUITABLE_NAME = new RegExp(
  [
    'police',
    'sheriff',
    'customs',
    'border protection',
    'immigration',
    'correctional',
    '\\bprison\\b',
    '\\bjail\\b',
    'courthouse annex',
    'military',
    '\\barmy\\b',
    '\\bnavy\\b',
    'air force',
    'barracks',
    'embassy',
    'consulate',
    'hospital',
    'medical cent',
    'emergency room',
    'school',
    'kindergarten',
    'childcare',
    'nursery',
    'power station',
    'substation',
    'water treatment',
  ].join('|'),
  'i',
);

const UNSUITABLE_TAGS: Array<[string, RegExp]> = [
  [
    'amenity',
    /^(police|prison|fire_station|hospital|clinic|doctors|school|kindergarten|childcare|courthouse)$/i,
  ],
  ['military', /./],
  ['office', /^(government|diplomatic)$/i],
  ['healthcare', /./],
  ['power', /./],
  ['landuse', /^(military|industrial)$/i],
];

export function isUnsuitable(name: string, tags: Record<string, string> = {}): boolean {
  if (UNSUITABLE_NAME.test(name)) return true;
  return UNSUITABLE_TAGS.some(([key, pattern]) => {
    const value = tags[key];
    return typeof value === 'string' && pattern.test(value);
  });
}
